# The Numpy Library

In [1]:
import numpy as np

In [7]:
#row sum
a=np.arange(12).reshape(3,4)
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [1]:
mylist=[1,2,3,4,5]
mylist
print(type(mylist))

<class 'list'>


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]    
# Creating a 2D list or list of lists
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [12]:
mymat=np.array(my_mat)
mymat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
mymat.shape

(4, 3)

In [15]:
mymat.ndim

2

In [16]:
mymat.dtype

dtype('int32')

In [17]:
my_arr = np.arange(0,11)                                 # It will return an array from 0 to 10
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
my_arr[10]   

10

In [19]:
my_arr[1:5]  

array([1, 2, 3, 4])

In [20]:
my_arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
my_arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
my_arr[:4]
      

array([0, 1, 2, 3])

In [23]:
my_arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [24]:
my_arr[0:5] = -5                                         
my_arr

array([-5, -5, -5, -5, -5,  5,  6,  7,  8,  9, 10])

In [27]:
arr_2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
arr_2d[0][0]

0

In [31]:
arr_2d[0:2,0:2]    

array([[0, 1],
       [3, 4]])

In [32]:
arr_2d[:2,1:]  

array([[1, 2],
       [4, 5]])

In [33]:
arr_2d = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
arr_2d[1:3,3:5]

array([[ 8,  9],
       [13, 14]])

In [35]:
arr_2d[2:4,0:2]

array([[10, 11],
       [15, 16]])

In [36]:
arr_cond = np.arange(0,11)

In [37]:
arr_cond>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [38]:
arr_cond[arr_cond>5]

array([ 6,  7,  8,  9, 10])

In [39]:
np.array(np.mat('1 2;3 4;5 6'))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [42]:
a[0]

1

In [43]:
a=np.array([1,2,3,4.0])
a

array([1., 2., 3., 4.])

In [48]:
print(np.array([1,2,3],dtype='float'))
print(np.array([1,2,3],dtype='U'))
print(np.array([12344,2,3],dtype='U3'))
print(np.array([1,2,3],dtype=complex))


[1. 2. 3.]
['1' '2' '3']
['123' '2' '3']
[1.+0.j 2.+0.j 3.+0.j]


In [51]:
x=np.array([('ram',26,10000.0),('shyam',31,50000)],dtype=[('name','<U11'),('age','int32'),('salary','<f4')])

In [52]:
x

array([('ram', 26, 10000.), ('shyam', 31, 50000.)],
      dtype=[('name', '<U11'), ('age', '<i4'), ('salary', '<f4')])

In [53]:
print("Row1",x[0])

Row1 ('ram', 26, 10000.)


In [56]:
two_arr=np.array([(1,2,3),(4,5,6),(7,8,9)])
two_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
print("shape of the 2-D array is",two_arr.shape)
print("the type of the 2-D array is",two_arr.dtype)
print("the size of array is",two_arr.size)
print("number of dimension inn 2-D array",two_arr.ndim)

shape of the 2-D array is (3, 3)
the type of the 2-D array is int32
the size of array is 9
number of dimension inn 2-D array 2


In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.ones((2,3,4),dtype=np.int16)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [66]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
r=np.eye(6)
r

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [72]:
arr=np.array([[1,2],[3,4]])
arr
print("Diagonal of above matrix",np.diag(arr))

Diagonal of above matrix [1 4]


In [73]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [74]:
print(np.arange(10,30,5))

[10 15 20 25]


In [76]:
print(np.arange(1,100,5))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [78]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [79]:
print("random number generation")
print(np.random.rand(2,3))

random number generation
[[0.34452238 0.41052175 0.38579097]
 [0.08773205 0.01773798 0.74949131]]


In [81]:
print("random number generation")
print(np.random.randn(4,3))

random number generation
[[ 0.50237709  1.70321833  0.85937709]
 [ 0.61173571  0.49232889  0.17582699]
 [ 1.03333418 -1.20525038 -0.17015694]
 [ 0.08783303  1.03111885 -0.10198512]]


In [90]:
#Arithemtic Scalar
b**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [95]:
x=b*10

In [96]:
x<30

array([ True,  True, False, False, False])

In [99]:
#Matric operations
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A)
print("-----")
print(B)

[[1 1]
 [0 1]]
-----
[[2 0]
 [3 4]]


In [101]:
add=A+B
sub=A-B
print(add)
print(sub)

[[3 1]
 [3 5]]
[[-1  1]
 [-3 -3]]


In [102]:
mul=A*B
mul

array([[2, 0],
       [0, 4]])

In [104]:
A=np.array([[2,3],[1,4]])
B=np.array([[6,4],[7,5]])
A.dot(B)

array([[33, 23],
       [34, 24]])

In [107]:

np.dot(A,B)

array([[33, 23],
       [34, 24]])

In [110]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
print("min value",a.min())
print("max value",a.max())
print("mean value",a.mean())
print("std Dev value",a.std())


min value 0
max value 11
mean value 5.5
std Dev value 3.452052529534663


In [113]:
a.shape

(3, 4)

In [114]:
#Column sum
a.sum(axis=0)

array([12, 15, 18, 21])

In [ ]:
#row sum
a=np.arange(12).reshape(3,4)
a
a.sum(axis=1)

In [116]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [117]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [121]:
np.sqrt(a,dtype="<f2")

array([[0.   , 1.   , 1.414, 1.732],
       [2.   , 2.236, 2.45 , 2.646],
       [2.828, 3.   , 3.162, 3.316]], dtype=float16)

In [124]:
np.argmax(a,axis=1)

array([3, 3, 3], dtype=int64)

In [126]:
#one dimensional arrays can be indexed,sliced and iterate
a=np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [127]:
a[2]

2.2857142857142856

In [128]:
a[2:5]

array([2.28571429, 2.92857143, 3.57142857])

In [131]:
a[:6:2]=100

In [132]:
A=np.arange(20).reshape(5,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [133]:
A[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [134]:
A[0:3,1]

array([1, 5, 9])

In [135]:
A[:,1]

array([ 1,  5,  9, 13, 17])

In [136]:
A[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
A[-1]

array([16, 17, 18, 19])

In [138]:
print(A[3])

[12 13 14 15]


In [141]:
print(A[3:])

[[12 13 14 15]
 [16 17 18 19]]


In [143]:
print(A[3,...])

[12 13 14 15]


In [145]:
B=np.arange(45).reshape(3,3,5)
print(B)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [146]:
B.shape

(3, 3, 5)

In [147]:
B[1,...]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [148]:
B[0,...]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [149]:
B[1,1:3,2:4]

array([[22, 23],
       [27, 28]])

In [150]:
B[2,0:2,2:4]

array([[32, 33],
       [37, 38]])

In [151]:
B[2,0:2,3:5]

array([[33, 34],
       [38, 39]])

In [157]:
#iterating
for axis1 in  B:
    print(axis1)
    print("="*10)
    for axis2 in axis1:
        print(axis2)
        print("="*10)
        for axis3 in axis2:
            print(axis3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4]
0
1
2
3
4
[5 6 7 8 9]
5
6
7
8
9
[10 11 12 13 14]
10
11
12
13
14
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[15 16 17 18 19]
15
16
17
18
19
[20 21 22 23 24]
20
21
22
23
24
[25 26 27 28 29]
25
26
27
28
29
[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
[30 31 32 33 34]
30
31
32
33
34
[35 36 37 38 39]
35
36
37
38
39
[40 41 42 43 44]
40
41
42
43
44


In [159]:
for i in range(3):
    print(B[i])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [161]:
for i in range(3):
    print("deparment",i)
    for j in range(3):
        print("employee",j)
        print(B[i,j])
        for k in range(5):
            print("emp",k)
            print(B[i,j,k])
    

deparment 0
employee 0
[0 1 2 3 4]
emp 0
0
emp 1
1
emp 2
2
emp 3
3
emp 4
4
employee 1
[5 6 7 8 9]
emp 0
5
emp 1
6
emp 2
7
emp 3
8
emp 4
9
employee 2
[10 11 12 13 14]
emp 0
10
emp 1
11
emp 2
12
emp 3
13
emp 4
14
deparment 1
employee 0
[15 16 17 18 19]
emp 0
15
emp 1
16
emp 2
17
emp 3
18
emp 4
19
employee 1
[20 21 22 23 24]
emp 0
20
emp 1
21
emp 2
22
emp 3
23
emp 4
24
employee 2
[25 26 27 28 29]
emp 0
25
emp 1
26
emp 2
27
emp 3
28
emp 4
29
deparment 2
employee 0
[30 31 32 33 34]
emp 0
30
emp 1
31
emp 2
32
emp 3
33
emp 4
34
employee 1
[35 36 37 38 39]
emp 0
35
emp 1
36
emp 2
37
emp 3
38
emp 4
39
employee 2
[40 41 42 43 44]
emp 0
40
emp 1
41
emp 2
42
emp 3
43
emp 4
44


In [164]:
B.max(axis=2)

array([[ 4,  9, 14],
       [19, 24, 29],
       [34, 39, 44]])

In [165]:
#it convert into list
B.flat

In [169]:
B.T.shape

(5, 3, 3)

In [172]:
B.shape

(3, 3, 5)

In [173]:
B.reshape(15,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [175]:
g=list(range(100000))
%timeit sum(g)

1.48 ms ± 122 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [177]:
g_array=np.array(g)
%timeit np.sum(g_array)

55.5 µs ± 707 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [184]:
a=np.array([1,2,3,4])
b=np.array([10,11,12,13])


In [185]:
a

array([1, 2, 3, 4])

In [186]:
b

array([10, 11, 12, 13])

In [188]:
a+b

array([11, 13, 15, 17])

In [189]:
type(a)

numpy.ndarray

In [190]:
a.dtype

dtype('int32')

In [191]:
a.ndim  

1

In [192]:
a.shape

(4,)

In [193]:
 f=5
 type(f)   

int

In [194]:
f=(5,6)
type(f)

tuple

In [195]:
a*b

array([10, 22, 36, 52])

In [196]:
a*10

array([10, 20, 30, 40])

In [197]:
#broadcasting
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [198]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [199]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [200]:
np.sum

<function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)>

In [202]:
np.sum(a)

10

In [203]:
a[0]

1

In [205]:
a[0]=5
a

array([5, 2, 3, 4])

In [206]:
a.dtype

dtype('int32')

In [207]:
a[0]=10.6
a

array([10,  2,  3,  4])

In [209]:
a.fill(-4.8)
a

array([-4, -4, -4, -4])

In [210]:
a=np.array([1,2,3,'f'])
a

array(['1', '2', '3', 'f'], dtype='<U11')

In [211]:
a.dtype

dtype('<U11')

In [213]:
c=np.array([[10,11,12],[20,21,22]])
c

array([[10, 11, 12],
       [20, 21, 22]])

c.ndim

In [214]:
c.ndim

2

In [215]:
c.shape

(2, 3)

In [216]:
c.size

6

In [217]:
#memory occupied
c.nbytes

24

In [218]:
a[0]

'1'

In [219]:
a[0]=10

In [220]:
c[0][0]=20

In [221]:
c

array([[20, 11, 12],
       [20, 21, 22]])

In [222]:
c[0,0]=1
c

array([[ 1, 11, 12],
       [20, 21, 22]])

In [223]:
c[0]

array([ 1, 11, 12])

In [224]:
c[1]

array([20, 21, 22])

In [225]:
c[0,]

array([ 1, 11, 12])

In [226]:
c[1,]

array([20, 21, 22])

In [227]:
c[1:,]

array([[20, 21, 22]])

In [228]:
#Slicing var[lower:upper:step]
a=np.array([10,11,12,13,14])
a


array([10, 11, 12, 13, 14])

In [229]:
a[1:3]

array([11, 12])

In [230]:
#Negative indices work also
a[1:-2]

array([11, 12])

In [231]:
a[-4:3]

array([11, 12])

In [232]:
#omitting indices
#grab the first three elements
a[:3]

array([10, 11, 12])

In [233]:
#grab last two elements
a[-2:]

array([13, 14])

In [234]:
#every other element
a[::2]

array([10, 12, 14])

In [ ]:
a[4:,4:]
a[0,3:5]
#to select the column
a[:,2]

a[2::2,::2]

In [236]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [254]:
a[1::2,:3:2]


array([[ 5,  7],
       [15, 17]])

In [249]:
a[4:,]
yellow=a[-1]
yellow

array([20, 21, 22, 23, 24])

In [247]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [250]:
a[1::2,0::2]

array([[ 5,  7,  9],
       [15, 17, 19]])

In [259]:
a[-1:,:-1]

array([[20, 21, 22, 23]])

In [264]:
a=np.arange(0,80,10)
a


array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [263]:
indices=[1,2,-3]
y=a[indices]
y

array([10, 20, 50])

In [265]:
#conditional mask
mask=a<30
y=a[mask]
y

array([ 0, 10, 20])

In [266]:
a=np.array([3,-1,-2,4,-6,8])
a

array([ 3, -1, -2,  4, -6,  8])

In [267]:
a<0

array([False,  True,  True, False,  True, False])

In [268]:
a[a<0]

array([-1, -2, -6])

In [269]:
negatives=a<0
a[negatives]

array([-1, -2, -6])

In [270]:
a[a<0]=0
a

array([3, 0, 0, 4, 0, 8])

In [271]:
a<8

array([ True,  True,  True,  True,  True, False])

In [272]:
a>3

array([False, False, False,  True, False,  True])

In [274]:
 (a<8).any()

True

In [277]:
#masking
a[(a>3)&(a<8)] 

array([4])

In [278]:
f=6
g=9
f+g
f.__add__(g)

15

In [279]:
np.nonzero(negatives)

(array([1, 2, 4], dtype=int64),)

In [280]:
a

array([3, 0, 0, 4, 0, 8])

In [281]:
a.sort()

In [285]:
b=np.array([2,3,20])
b

array([ 2,  3, 20])

In [286]:
a>b

array([False, False, False])

In [287]:
#is gives the postion
np.nonzero(a>b)

(array([], dtype=int64),)

In [288]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [289]:
a[[0,1,2,3,4],[0,1,2,3,4]]

array([ 0,  6, 12, 18, 24])

In [292]:
a[2:,[0,2,4]]

array([[10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [293]:
a[[0,2,4],2]

array([ 2, 12, 22])

In [297]:
#boolean mask
mask=np.array([1,0,1,0,1],dtype=bool)
a[mask,2]

array([ 2, 12, 22])

In [300]:
a=np.array([10,1,20])
a

array([10,  1, 20])

In [302]:
subset=a[[0,2]]
subset

array([10, 20])

In [303]:
a.flags.owndata

True

In [304]:
subset.flags.owndata

True

In [305]:
a is subset

False

In [306]:
subset[0]=-1
subset

array([-1, 20])

In [307]:
a

array([10,  1, 20])

In [309]:
a[-1]=100
a

array([ 10,   1, 100])

In [310]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [312]:
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

In [313]:
a[a%3==0]

array([], shape=(0, 5, 5), dtype=int32)

In [314]:
a%3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]], dtype=int32)

In [315]:
a%3==0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [317]:
np.nan

nan

In [321]:
print(a)
output=np.empty_like(a)
output

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [329]:
output=np.empty_like(a,dtype="float")
output

array([[2.37663529e-312, 2.05833592e-312, 2.41907520e-312,
        2.56761491e-312, 1.93101617e-312],
       [1.06099790e-312, 1.08221785e-312, 9.33678148e-313,
        1.03977794e-312, 1.10343781e-312],
       [1.97345609e-312, 2.12199579e-313, 2.37663529e-312,
        2.05833592e-312, 2.41907520e-312],
       [2.56761491e-312, 1.93101617e-312, 1.14587773e-312,
        1.10343781e-312, 9.33678148e-313],
       [1.16709769e-312, 1.12465777e-312, 1.97345609e-312,
        4.83245800e+276,             nan]])

In [330]:
output.fill(np.nan)
output

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [331]:
output.fill(np.nan)
output

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [325]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [332]:
#Method-1
mask=a%3==0
output[mask]=a[mask]
output

array([[ 0., nan, nan,  3., nan],
       [nan,  6., nan, nan,  9.],
       [nan, nan, 12., nan, nan],
       [15., nan, nan, 18., nan],
       [nan, 21., nan, nan, 24.]])

In [333]:
#finding and covering-Method-2
np.where(a%3==0,a,np.nan)

array([[ 0., nan, nan,  3., nan],
       [nan,  6., nan, nan,  9.],
       [nan, nan, 12., nan, nan],
       [15., nan, nan, 18., nan],
       [nan, 21., nan, nan, 24.]])

In [334]:
a[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [335]:
output[mask]

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24.])

In [337]:
#Multi-Dimensional Array
np.nan+6

nan

In [338]:
np.sum([1,np.nan,9])

nan

In [339]:
np.nansum([1,np.nan,9])

10.0

In [340]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [341]:
np.sum(a)

6

In [342]:
a.sum()

6

In [344]:
a=np.arange(24).reshape(6,4)
a  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [345]:
a.shape

(6, 4)

In [346]:
a.mean(axis=0).shape


(4,)

In [347]:
a.mean(axis=1).shape

(6,)

In [348]:
channel_means=a.mean(axis=1)
channel_means

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [349]:
#Min/Max methods
a=np.array([2.,3.,0.,1.])
a.min(axis=0)

0.0

In [350]:
np.min(a,axis=0)

0.0

In [351]:
#ARGMIN to find index of minimum value
a.argmin(axis=0)

2

In [352]:
np.argmin(a,axis=0)

2

In [353]:
#Max
a=np.array([2,3,0,1])
a.max(axis=0)

3

In [354]:
#argmax
np.argmax(a,axis=0)

1

In [382]:
a=np.arange(24).reshape(6,4)
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [369]:
a[:,:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [371]:
print(a.mean(),a.min(),a.max(),a.std())

11.5 0 23 6.922186552431729


In [384]:

y=np.max(a)
y

23

In [385]:
x=np.argmax(a)
x

23

In [378]:
import numpy as np
a=[0,0,1,0]
maximum=max(a)
maximum


1

In [377]:
index=np.argmax(a)
index

2

In [386]:
arr = np.arange(0,16)                                # Using reshape we can change the dimensions of the array
arr_2D = arr.reshape(4,4) 
arr_2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [387]:
arr_2D.flatten()  # Flatten is used to convert a 2D array to 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [388]:
arr_2D.transpose()    

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [389]:
arr_x = np.array([[1,2,3,4],[5,6,7,8]])                # Lets create 2 arrays
arr_y = np.array([[21,22,23,24],[25,26,27,28]])

In [392]:
arr_x[1:,]

array([[5, 6, 7, 8]])

In [397]:
arr_z = np.concatenate((arr_x, arr_y), axis=0)         # Join 2 arrays along rows
arr_z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [400]:
np.concatenate((arr_x, arr_y), axis=1)    

array([[ 1,  2,  3,  4, 21, 22, 23, 24],
       [ 5,  6,  7,  8, 25, 26, 27, 28]])

In [401]:
np.hsplit(arr_z, 2) 

[array([[ 1,  2],
        [ 5,  6],
        [21, 22],
        [25, 26]]), array([[ 3,  4],
        [ 7,  8],
        [23, 24],
        [27, 28]])]

In [402]:
np.vsplit(arr_z, 2) 

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[21, 22, 23, 24],
        [25, 26, 27, 28]])]

In [416]:
a=np.array([[10,20],[1,2]])
a

array([[10, 20],
       [ 1,  2]])

In [420]:
np.sort(a,axis=0)


array([[ 1,  2],
       [10, 20]])

In [421]:
a[1:]

array([[10, 20]])

In [422]:
a[:1]

array([[1, 2]])

In [423]:
a[::-1]

array([[10, 20],
       [ 1,  2]])

In [3]:
import numpy as np
my_list=[-17,0,4,5,9]
my_array_from_list=np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

###Difference between python and Numpy Datastructures

In [4]:
my_tuple=(14,-3.45,5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.45+0.j,  5.  +7.j])

In [5]:
my_tuple*6


(14,
 -3.45,
 (5+7j),
 14,
 -3.45,
 (5+7j),
 14,
 -3.45,
 (5+7j),
 14,
 -3.45,
 (5+7j),
 14,
 -3.45,
 (5+7j),
 14,
 -3.45,
 (5+7j))

In [6]:
np.array(my_tuple)*6

array([ 84.  +0.j, -20.7 +0.j,  30. +42.j])

Intrinsic Numpy array ceraetion using Numpy method

In [7]:
import numpy as np
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
np.arange(7).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [9]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [10]:
len(np.arange(10,23))

13

In [11]:
size_val=np.arange(10,23)
size_val.size

13

In [13]:
np.arange(10,23).size

13

In [14]:
np.arange(10,23,4)

array([10, 14, 18, 22])

In [15]:
np.arange(26,step=5)

array([ 0,  5, 10, 15, 20, 25])

linspace(),zeros(),ones()

In [17]:
np.linspace(5,15,9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [18]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
np.zeros(11,dtype="int64")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [22]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Slicing Array

In [23]:
my_vector=np.array([-17,-4,0,2,21,37,105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [24]:
my_vector[0]

-17

In [25]:
my_vector[0]=100

In [26]:
my_vector[-3]

21

Two Dimensional Array

In [27]:
my_array=np.arange(35)
my_array.shape=(7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [28]:
my_array[2]

array([10, 11, 12, 13, 14])

In [29]:
my_array[-2]

array([25, 26, 27, 28, 29])

In [30]:
my_array[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [32]:
my_array[:4]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
my_array[5,2]

27

##Three Dimensional Array

In [34]:
my_3D_array=np.arange(70)
my_3D_array.shape=(2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [35]:
my_3D_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [36]:
my_3D_array[1,3]

array([50, 51, 52, 53, 54])

In [37]:
my_3D_array[1,3,2]

52

Broadcasting 

In [38]:
my_3d_array=np.arange(70)
my_3d_array.shape=(2,7,5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [39]:
my_3d_array.shape

(2, 7, 5)

In [40]:
my_3d_array.ndim

3

In [41]:
my_3d_array.size

70

In [12]:
import pandas as pd
fruits = [['Apple','Banana'],['Coconut','Dates'],['carrot','papaya'],['orange','beans']]
fruits_df = pd.DataFrame(fruits,columns=['fruits','vegatables'])         # columns is used to set the column name
fruits_df

fruits vegatables
0    Apple     Banana
1  Coconut      Dates
2   carrot     papaya
3   orange      beans

In [15]:
fruits={'Name':['XXX','YYY','ZZZ'],'Age':[12,23,44],'weight':[5,4,6]}
fruits=pd.DataFrame(fruits)

In [16]:
fruits

Name  Age  weight
0  XXX   12       5
1  YYY   23       4
2  ZZZ   44       6

In [17]:
fruits['Score']=[4,5,8]

In [18]:
fruits

Name  Age  weight  Score
0  XXX   12       5      4
1  YYY   23       4      5
2  ZZZ   44       6      8

In [19]:
fruits['Score']

0    4
1    5
2    8
Name: Score, dtype: int64

In [29]:
fruits.iloc[:,:2]

Age  weight
Name             
XXX    12       5
YYY    23       4
ZZZ    44       6